name: tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'main'

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        
      - name: "Set up Go"  
        uses: actions/setup-go@v5

      - name: "Prepare dependencies"
        run: go mod download

      - name: "Run tests"
        run: go test -race ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: "Check coverage"
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yaml
          ## when token is not specified (value '') this feature is turned off
          ## in this example badge is created and committed only for main branch
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          ## name of branch where badges are stored
          ## ideally this should be orphan branch (see below how to create this branch)
          git-branch: badges 