name: tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        
      - name: "Set up Go"  
        uses: actions/setup-go@v5

      - name: "Prepare dependencies"
        run: go mod download

      - name: "Run tests"
        run: go test -race ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: "Check coverage"
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yaml